### PR TITLE
Fixed for game update 1.1.54

### PR DESCRIPTION
**Pull request by CrafterBotOfficial**
Minor changes to fix Lights Camera Action for the latest version of Gorilla Tag.

Changes:
-Increased version number
-Moved field for the palm & offline VRRig gameobject paths to PluginInfo.cs
-Changed paths palm & vrrig for new game update

I'm not using the GorillaTagger.Instance.OfflineRig to find the local player, as Another-Axiom has been messing around with the VRRigs a lot recently. So I would be worried about the field being changed. The GorillaScienceLib's source code was never posted so their may be some minor issues with the solution. However after decompiling GorillaScienceLib it appears to not contain any code that would be broken.  All modules have been tested on my machine and YourTrash's machine, though additional testing never hurts.

### CODE REVIEW

**Comment by KyleTheScientist** [comment]
Why are there 8 commits? You changed one thing 😂

**Comment by CrafterBotOfficial** [comment]
I'm not a Git pro >:(

**Comment by KyleTheScientist** [comment]
`git add --all`
`git commit -m "Fixed for game update"`
`git push`
:)

**Comment by CrafterBotOfficial** [comment]
That's fancy, I am just using Github Desktop.

**Comment by KyleTheScientist** [comment]
You can also do git stuff in Visual Studio in the source control pane on the right. I don't think I've ever seen anyone use GitHub desktop. It is a sad application.

**Comment by CrafterBotOfficial** [comment]
I've used the ``git clone`` command before, but that's basically it.

**Pull request closed without merging**
